<html>

  <head>
    <style>
      #s {
      font-family: Arial, Helvetica, sans-serif;
      border-collapse: collapse;
      width: 50%;
    }

    #s td, #customers th {
      border: 1px solid #ddd;
      padding: 8px;
    }

    #s tr:nth-child(even){background-color: #f2f2f2;}

    #s tr:hover {background-color: #ddd;}

    #s th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: left;
      background-color: #04AA6D;
      color: white;
    }    
    </style>
  </head>

  <body>
    <h1>
      <a href="https://barney.gonzaga.edu/~pburks/Final/proj.php">Home</a>
    </h1>
    <h2>Interesting Queries</h2>

    <?php
      // get credentials
      $config = parse_ini_file("../../private/projconfig.ini");
      $server = $config["servername"];
      $username = $config["username"];
      $password = $config["password"];
      $database = "pburks_DB";

      // connect
      $conn = mysqli_connect($server, $username, $password, $database);
      if (!$conn) {
        die("Connection failed: " . mysqli_connect_error()); 
      }
      
      // every concert query
      $query =  "SELECT DISTINCT c1.venue, c1.artist, c1.date " .
                "FROM concert c1, concert c2 " .
                "WHERE c1.date != c2.date or c1.venue != c2.venue " .
                "ORDER BY c1.date DESC;";

      $stmt = $conn->stmt_init();
      $stmt->prepare($query);
      $stmt->execute();
      $stmt->bind_result($venue, $artist, $date);
    
      echo "<p style='font-weight: bold;'>Every Concert by Date</p>";
      echo $query;
      echo "</p>\n";
      echo "<table id='s'><tr><th>Venue</th><th>Artist</th><th>Date</th></tr>";
      while ($stmt->fetch()) {
        echo "<tr>";
        echo "<td>" . $venue . "</td><td>" . $artist . "</td><td>" . $date . "</td>";
        echo "</tr>";
      }
      echo "</table>";

      echo "</p>\n";
      $stmt->close();

      // avg price of concerts in each country
      $query =  "SELECT v.country as country, ROUND(AVG(price), 2) " .
                "FROM concert c JOIN venue v ON (c.venue = v.name_) " .
                "GROUP BY v.country;";
      
      $stmt = $conn->stmt_init();
      $stmt->prepare($query);
      $stmt->execute();
      $stmt->bind_result($country, $avgprice);

      echo "<p style='font-weight: bold;'>AVG Price of a Concert per Country (UDS)</p>";
      echo $query;
      echo "</p>\n";
      echo "<table id='s'><tr><th>Country</th><th>AVG Price (USD)</th></tr>";
      while ($stmt->fetch()) {
        echo "<tr>";
        echo "<td>" . $country . "</td><td>" . $avgprice . "</td>";
        echo "</tr>";
      }
      echo "</table>";

      echo "</p>\n";
      $stmt->close();

      // avg revenue generated by each venue per concert, judging by avg price of tickets multiplied by number of seats
      $query =  "SELECT v.name_ as venue, ROUND(AVG(price) * num_seats, 2) as est_rev " .
                "FROM concert c JOIN venue v ON (c.venue = v.name_) " .
                "GROUP BY v.name_ " .
                "ORDER BY est_rev DESC;";
      
      $stmt = $conn->stmt_init();
      $stmt->prepare($query);
      $stmt->execute();
      $stmt->bind_result($venue, $est_rev);

      echo "<p style='font-weight: bold;'>Estimated Revenue Per Concert (USD)</p>";
      echo $query;
      echo "</p>\n";
      echo "<table id='s'><tr><th>Venue</th><th>Estimated Revenue(USD)</th></tr>";
      while ($stmt->fetch()) {
        echo "<tr>";
        echo "<td>" . $venue . "</td><td>" . $est_rev . "</td>";
        echo "</tr>";
      }
      echo "</table>";

      echo "</p>\n";
      $stmt->close();

      // find the most popular artist on the database
      $query =  "SELECT artist, COUNT(*) as max_count " .
                "FROM concert " .
                "GROUP BY artist " .
                "HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM concert GROUP BY artist)";
      
      $stmt = $conn->stmt_init();
      $stmt->prepare($query);
      $stmt->execute();
      $stmt->bind_result($artist, $max_count);

      echo "<p style='font-weight: bold;'>Most Popular Artist on the Database</p>";
      echo $query;
      echo "</p>\n";
      echo "<table id='s'><tr><th>Artist</th><th>Concert Mentions</th></tr>";
      while ($stmt->fetch()) {
        echo "<tr>";
        echo "<td>" . $artist . "</td><td>" . $max_count . "</td>";
        echo "</tr>";
      }
      echo "</table>";

      echo "</p>\n";
      $stmt->close();

      // find users who attended the same concert
      $query =  "SELECT DISTINCT c1.username, c2.username, c1.date, c1.venue, c1.artist, ROUND((c1.price - c2.price), 2) as price_diff " .
                "FROM concert c1, concert c2 " . 
                "WHERE c1.venue = c2.venue and c1.date = c2.date and c1.username != c2.username " .
                "ORDER BY c1.date DESC, artist DESC;";
      
      $stmt = $conn->stmt_init();
      $stmt->prepare($query);
      $stmt->execute();
      $stmt->bind_result($user1, $user2, $date, $venue, $artist, $price_diff);

      echo "<p style='font-weight: bold;'>Users who Attended the Same Concerts</p>";
      echo $query;
      echo "</p>\n";
      echo "<table id='s'><tr><th>User 1</th><th>User 2</th><th>Date</th><th>Venue</th><th>Artist</th><th>Price Difference</th></tr>";
      while ($stmt->fetch()) {
        echo "<tr>";
        echo "<td>" . $user1 . "</td><td>" . $user2 . "</td><td>" . $date . "</td><td>" . $venue . "</td><td>" . $artist . "</td><td>" . $price_diff . "</td>";
        echo "</tr>";
      }
      echo "</table>";

      echo "</p>\n";
      $stmt->close();

      // find users who have never attended a concert
      $query =  "SELECT username " .
                "FROM user LEFT OUTER JOIN concert using (username) " . 
                "WHERE concert.date IS NULL;";
      
      $stmt = $conn->stmt_init();
      $stmt->prepare($query);
      $stmt->execute();
      $stmt->bind_result($username);

      echo "<p style='font-weight: bold;'>Users who have Never Attended a Concert</p>";
      echo $query;
      echo "</p>\n";
      echo "<table id='s'><tr><th>Username</th></tr>";
      while ($stmt->fetch()) {
        echo "<tr>";
        echo "<td>" . $username . "</td>";
        echo "</tr>";
      }
      echo "</table>";

      echo "</p>\n";
      $stmt->close();

      $conn->close();
    ?>

  </body>
</html>